---
header: |
  #!/usr/bin/env ruby
  # frozen_string_literal: true

  require "yaml"

subject: |
  YAML.load_file("%{path}")

contexts:
  path:
    - config/rubocop/performance.yml
    - config/rubocop/rails.yml
    - config/rubocop/rake.yml
    - config/rubocop/rspec.yml
    - config/rubocop.yml

actuals:
  - "%{subject}.keys.sort"
