inherit_from: config/rubocop.yml

AllCops:
  Exclude:
    - vendor/**/*.rb
    - vendor/bundle/**/*

  NewCops: enable
  TargetRubyVersion: 2.7

require:
  - rubocop-md
  - rubocop-rake

Layout/LineLength:
  Exclude:
    - test.rb
